#version 460

layout(set = 0, binding = 0) uniform ParameterUBO {
	vec2 lo_xy;
	vec2 hi_xy;

	vec2 julia_c;
	int subdivisionCount;
} ubo;

layout(rgba16f,set = 0, binding = 1) uniform image2D image;

struct Ray {
	vec3 orig;
	vec3 dir;
};

const int NUMDIM = 3;

bool cubeIntersection(Ray r, vec3 lo, vec3 hi, out float intersectionT) {
	float tVal[NUMDIM*2];
	for (int i = 0; i < NUMDIM; ++i) {
		if (r.dir[i] != 0.0f) {
			tVal[i] = (lo[i] - r.orig[i])/r.dir[i];
			tVal[NUMDIM+i] = (hi[i] - r.orig[i])/r.dir[i];
		} else {
			tVal[i] = -1.;
			tVal[NUMDIM+i] = -1.;
		}
	}
	
	float minT = 1./0.;
	for (int i = 0; i < NUMDIM*2; ++i) {
		if (tVal[i] >= 0.) {
			vec3 pos = r.orig + r.dir*tVal[i];
			bool isValid = true;
			for (int j = 0; j < NUMDIM; ++j) {
				if (j != (i%NUMDIM)) {
					isValid = isValid && (lo[j] <= pos[j]) && (pos[j] <= hi[j]);
				}
			}

			if (isValid) {
				minT = min(minT, tVal[i]);
			}
		}
	}

	if (isinf(minT)) {
		return false;
	}
	
	intersectionT = minT;
	return true;
}

const int SIERPINSKI_CUBE_DELTA_CNT = 20;
vec3 deltas[20] = {
	{1, 1, 0},
	{1, -1, 0},
	{-1, 1, 0},
	{-1, -1, 0},

	{0, 1, 1},
	{0, 1, -1},
	{0, -1, 1},
	{0, -1, -1},

	{1, 0, 1},
	{-1, 0, 1},
	{1, 0, -1},
	{-1, 0, -1},

	{1, 1, 1},
	{1, 1, -1},
	{1, -1, 1},
	{1, -1, -1},
	{-1, 1, 1},
	{-1, 1, -1},
	{-1, -1, 1},
	{-1, -1, -1},
};

/*
bool scubeIntersection(Ray r, vec3 lo, vec3 hi, int remainingDivisions, out float intersectionT) {
	bool hit = cubeIntersection(r, lo, hi, intersectionT);
	if (remainingDivisions == 0 || !hit) {
		return hit;
	}

	float miniIntersections[SIERPINSKI_CUBE_DELTA];
	
	vec3 new_lo = lo/3.;
	vec3 new_hi = hi/3.;
	for (int i = 0; i < SIERPINSKI_CUBE_DELTA; ++i) {
		if (!scubeIntersection(r, new_lo + deltas[i]/3., new_hi + deltas[i]/3., remainingDivisions-1, miniIntersections[i])) {
			miniIntersections[i] = 1./0.;
		}
	}

	intersectionT = 1./0.;
	for (int i = 0; i < SIERPINSKI_CUBE_DELTA; ++i) {
		intersectionT = min(intersectionT, miniIntersections[i]);
	}

	return !isinf(intersectionT);
}
*/
bool scubeIntersection(Ray r, vec3 lo, vec3 hi, int remainingDivisions, out float intersectionT) {
	intersectionT = 1./0.;

	const int BUF_SIZE = 77;
	int buf_index = 0;
	int div_vals[BUF_SIZE];
	vec3 lo_vals[BUF_SIZE];
	vec3 hi_vals[BUF_SIZE];
	
	div_vals[0] = remainingDivisions;
	lo_vals[0] = lo;
	hi_vals[0] = hi;

	while (buf_index >= 0) {
		if (div_vals[buf_index] == 0) {
			float currT;
			if (cubeIntersection(r, lo_vals[buf_index], hi_vals[buf_index], currT)) {
				intersectionT = min(intersectionT, currT);
			}
			--buf_index;
		} else {
			vec3 curr_lo = lo_vals[buf_index];
			vec3 curr_hi = hi_vals[buf_index];

			float currT;
			if (cubeIntersection(r, curr_lo, curr_hi, currT)) {
				int new_div_val = div_vals[buf_index] - 1;
				vec3 movement = (curr_hi - curr_lo)/3.;
				for (int i = 0; i < SIERPINSKI_CUBE_DELTA_CNT; ++i) {
					div_vals[buf_index] = new_div_val;
					lo_vals[buf_index] = mix(curr_lo, curr_hi, 1./3.) + movement*deltas[i];
					hi_vals[buf_index] = mix(curr_lo, curr_hi, 2./3.) + movement*deltas[i];
					++buf_index;
				}
			}
			--buf_index;
		}
	}
	return !isinf(intersectionT);
}

float imageWidth = imageSize(image).x;
float imageHeight = imageSize(image).y;

float focalLength = 1.0f;

float viewportHeight = 2.0f;
float viewportWidth = viewportHeight * (float(imageWidth)/float(imageHeight));

vec3 cameraCenter = vec3(0.0, 0.0, -4.);

vec3 viewportU = vec3(viewportWidth, 0, 0);
vec3 viewportV = vec3(0, -viewportHeight, 0);
vec3 pixelDeltaU = viewportU/imageWidth;
vec3 pixelDeltaV = viewportV/imageHeight;

vec3 viewportUpperLeft = cameraCenter + vec3(0, 0, focalLength) - viewportU/2 - viewportV/2;
vec3 pixel00Loc = viewportUpperLeft + 0.5 * (pixelDeltaU + pixelDeltaV);

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);

    if(texelCoord.x >= size.x || texelCoord.y >= size.y) {
		return;
	}
	vec3 pixelCenter = pixel00Loc + (texelCoord.x * pixelDeltaU) + (texelCoord.y * pixelDeltaV);

	vec3 rayDirection = normalize(pixelCenter - cameraCenter);
	vec3 rayOrig = cameraCenter;

	Ray ray = Ray(rayOrig, rayDirection);

	float intersectionT;
	vec4 color = vec4(0, 0, 0, 1);

	if (scubeIntersection(ray, vec3(-1, -1, -1), vec3(1, 1, 1), 3, intersectionT)) {
	//if (cubeIntersection(ray, vec3(-1, -1, -1), vec3(1, 1, 1), intersectionT)) {
		color = vec4(1, 1, 1, 1);
	}
	imageStore(image, texelCoord, color);
}
