#version 460

layout(set = 0, binding = 0) uniform ParameterUBO {
	vec2 lo_xy;
	vec2 hi_xy;
	vec2 julia_c;

	int subdivisionCount;
} ubo;
struct Vertex {
	vec4 pos;
	vec4 color;
};
layout(std430, set = 1, binding = 0) buffer VertexBuffer {
	Vertex vertices[];
};

layout(std430, set = 1, binding = 1) buffer IndexBuffer {
	uint indices[];
};

vec2 trime(int a, int n) {
	vec2 deltas[3] = {
		{0, 1./3.},
		{inversesqrt(3)*(-0.5f), -1./6.},
		{inversesqrt(3)*(0.5f), -1./6.},
	};
	vec2 acc = vec2(0, 0);
	for (int i = 0; i < n; ++i) {
		acc /= 2.0f;
		acc += deltas[a%3];
		a /= 3;
	}
	return acc;
}

layout (local_size_x = 64, local_size_y = 1) in;
void main() {
	/*
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);
    if(texelCoord.x >= size.x || texelCoord.y >= size.y) {
		return;
	}
	*/
	int currIndex = int(gl_GlobalInvocationID.x);
	if (currIndex >= pow(3, ubo.subdivisionCount)) {
		return;
	}

	vec2 val = trime(currIndex, ubo.subdivisionCount);

	float r = (2.0/3.0)*pow(2.0f, -ubo.subdivisionCount);
	vertices[3*currIndex + 0].pos.xy = val + vec2(0, r);
	vertices[3*currIndex + 1].pos.xy = val + vec2(sqrt(3.0f)/2.0f*r, -0.5f*r);
	vertices[3*currIndex + 2].pos.xy = val + vec2(-sqrt(3.0f)/2.0f*r, -0.5f*r);
	for (int i = 0; i < 3; ++ i) {
		vertices[3*currIndex + i].pos.x = mix(-1, 1, (vertices[3*currIndex + i].pos.x - ubo.lo_xy.x)/(ubo.hi_xy.x-ubo.lo_xy.x));
		vertices[3*currIndex + i].pos.y = mix(1, -1,  (vertices[3*currIndex + i].pos.y - ubo.lo_xy.y)/(ubo.hi_xy.y-ubo.lo_xy.y));
		vertices[3*currIndex + i].pos.z = 0.0f;
		vertices[3*currIndex + i].pos.w = 1.0f;
	}

	vec4 white = vec4(1, 1, 1, 1);
	vertices[3*currIndex + 0].color = white;
	vertices[3*currIndex + 1].color = white;
	vertices[3*currIndex + 2].color = white;
	vertices[3*currIndex + 3].color = white;

	indices[3*currIndex + 0] = 3*currIndex + 0;
	indices[3*currIndex + 1] = 3*currIndex + 1;
	indices[3*currIndex + 2] = 3*currIndex + 2;
}
