#version 460

layout(set = 0, binding = 0) uniform ParameterUBO {
	vec2 lo_xy;
	vec2 hi_xy;
	vec2 julia_c;

	int subdivisionCount;
} ubo;
struct Vertex {
	vec4 pos;
	vec4 color;
};
layout(std430, set = 1, binding = 0) buffer VertexBuffer {
	Vertex vertices[];
};

layout(std430, set = 1, binding = 1) buffer IndexBuffer {
	uint indices[];
};


vec3 deltas[20] = {
	{1, 1, 0},
	{1, -1, 0},
	{-1, 1, 0},
	{-1, -1, 0},

	{0, 1, 1},
	{0, 1, -1},
	{0, -1, 1},
	{0, -1, -1},

	{1, 0, 1},
	{-1, 0, 1},
	{1, 0, -1},
	{-1, 0, -1},

	{1, 1, 1},
	{1, 1, -1},
	{1, -1, 1},
	{1, -1, -1},
	{-1, 1, 1},
	{-1, 1, -1},
	{-1, -1, 1},
	{-1, -1, -1},
};

vec3 corners[8] = {
	{1, 1, 1},
	{-1, 1, 1},
	{-1, -1, 1},
	{1, -1, 1},

	{1, -1, -1},
	{-1, -1, -1},
	{-1, 1, -1},
	{1, 1, -1},
};

int cubeIndices[36] = {
	0, 1, 2,
	2, 3, 0,

	0, 7, 6,
	6, 1, 0,

	1, 6, 5,
	5, 2, 1,

	3, 2, 4,
	2, 5, 4,

	0, 3, 7,
	3, 4, 7,
	
	4, 5, 6,
	4, 6, 7,
};


vec3 cubify(int a, int n) {
	vec3 acc = vec3(0, 0, 0);
	for (int i = 0; i < n; ++i) {
		acc += deltas[a%20];
		acc /= 3.0f;
		a /= 20;
	}
	return acc;
}

float rand(vec2 co){
    return fract(sin(dot(co, vec2(12.9898, 18.233))) * 43758.5453);
}

layout (local_size_x = 64, local_size_y = 1) in;
void main() {
	/*
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);
    if(texelCoord.x >= size.x || texelCoord.y >= size.y) {
		return;
	}
	*/
	int currIndex = int(gl_GlobalInvocationID.x);
	if (currIndex >= pow(20, ubo.subdivisionCount)) {
		return;
	}

	vec3 val = cubify(currIndex, ubo.subdivisionCount);

	float r = pow(3.0f, -ubo.subdivisionCount);
	for (int i = 0; i < 8; ++ i) {
		vertices[8*currIndex + i].pos.xyz = val + r*.5f * corners[i];
		/*
		vertices[4*currIndex + i].pos.x = mix(-1, 1, (vertices[3*currIndex + i].pos.x - ubo.lo_xy.x)/(ubo.hi_xy.x-ubo.lo_xy.x));
		vertices[4*currIndex + i].pos.y = mix(1, -1,  (vertices[3*currIndex + i].pos.y - ubo.lo_xy.y)/(ubo.hi_xy.y-ubo.lo_xy.y));
		*/
		vertices[8*currIndex + i].pos.w = 1.0f;
		// vertices[8*currIndex + i].color = vec4(0.5f+z_val, 0, 0.5f+z_val, 1);
		// vertices[8*currIndex + i].color = vertices[8*currIndex+i].pos + vec4(0.5f, 0.5f, 0.5f, 0);
		// vertices[8*currIndex + i].color = fract(vertices[8*currIndex+i].pos*3);
		vertices[8*currIndex + i].color = fract(vertices[8*currIndex+i].pos*89789.0f) + vec4(0, 0, 0, 1);
		/*
		vec3 a = 100*vertices[8*currIndex + i].pos.xyz;
		vertices[8*currIndex + i].color.r = rand(a.xy);
		vertices[8*currIndex + i].color.g = rand(a.yz);
		vertices[8*currIndex + i].color.b = rand(a.zx);
		vertices[8*currIndex + i].color.a = (4./3.)*(a.x*a.x + a.y*a.y + a.z*a.z);
		*/
	}

	for (int i = 0; i < 36; ++i) {
		indices[36*currIndex + i] = 8*currIndex + cubeIndices[i];
	}
}
